[versions]
# android sdk versions
compileSdk = "33"
coreMinSdk = "19"
minSdk = "21"
targetSdk = "33"
# build
gradleBuild = "7.3.1"
buildTools = "33.0.0"
# kotlin
dokka = "1.7.20"
kotlinCore = { require = "1.7.20" }
kotlinCoroutines = { require = "1.6.4" }
kotlinxSerialization = "1.4.0"
# compose
compose = "1.3.1"
composeCompiler = "1.3.2"
composejb = "1.3.0-beta03"
# androidx
activity = "1.6.1"
cardview = "1.0.0"
constraintLayout = "2.1.4"
core = "1.9.0"
lifecycle = { require = "2.5.1" }
navigation = "2.5.2"
recyclerView = "1.2.1"
# google
material = "1.7.0"
# other
accompanist = "0.27.1"
fastAdapter = "5.7.0"
gradleMvnPublish = "0.18.0"
iconics = "5.3.3"
itemAnimators = "1.1.0"
ivy = "2.5.0"
materialDrawer = "9.0.1"
okhttp = "4.10.0"

[libraries]
# build
gradle-build = { module = "com.android.tools.build:gradle", version.ref = "gradleBuild" }
# kotlin
dokka-plug = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlinCore" }
kotlin-plug = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinCore" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinCoroutines" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
# compose
compose-androidx-runtime-core = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
compose-androidx-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }
compose-androidx-ui-core = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-androidx-foundation-core = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-androidx-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "compose" }
compose-androidx-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-jb-plug = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "composejb" }
# androidx
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
androidx-cardView = { module = "androidx.cardview:cardview", version.ref = "cardview" }
androidx-constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-navigation-plug = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigation" }
androidx-navigation = { module = "androidx.navigation:navigation-fragment", version.ref = "navigation" }
androidx-recyclerView = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerView" }
# google
google-material = { module = "com.google.android.material:material", version.ref = "material" }
# other
accompanist-insets-ui = { module = "com.google.accompanist:accompanist-insets-ui", version.ref = "accompanist" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
fastAdapter-core = { module = "com.mikepenz:fastadapter", version.ref = "fastAdapter" }
gradleMvnPublish-plug = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "gradleMvnPublish" }
iconics-core = { module = "com.mikepenz:iconics-core", version.ref = "iconics" }
itemAnimators-core = { module = "com.mikepenz:itemanimators", version.ref = "itemAnimators" }
ivy-core = { module = "org.apache.ivy:ivy", version.ref = "ivy" }
materialDrawer-core = { module = "com.mikepenz:materialdrawer", version.ref = "materialDrawer" }
okhttp-core = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

[bundles]
accompanist = ["accompanist-insets-ui", "accompanist-systemuicontroller"]
androidx-lifecycle = ["androidx-lifecycle-livedata-ktx", "androidx-lifecycle-viewmodel-ktx"]
compose-androidx = ["compose-androidx-runtime-core", "compose-androidx-runtime-livedata", "compose-androidx-ui-core", "compose-androidx-ui-tooling", "compose-androidx-foundation-core", "compose-androidx-foundation-layout", "compose-androidx-material"]